services:
  asr:
    image: siewsugar-asr:latest
    container_name: asr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]